<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cupboard_drawers">

<xacro:property name="wall_thickness" value="0.05"/>
<xacro:property name="total_height" value="1.5"/>
<xacro:property name="total_width" value="1.5"/>
<xacro:property name="total_depth" value="1.0"/>
<xacro:property name="num_drawers" value="3"/>
<xacro:property name="drawer_spacing" value="0.005"/>

<xacro:macro name="ori_geo" params="width depth height">
  <origin rpy="0 0 0" xyz="0 0 0"/>
  <geometry>
    <box size="${width} ${depth} ${height}"/>
  </geometry>
</xacro:macro>

<xacro:macro name="wall" params="prefix width height thickness">
  <link name="${prefix}_wall">
    <contact>
      <lateral_friction value="1.0"/>
    </contact>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
       <mass value="0.2"/>
       <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
    <visual>
      <xacro:ori_geo width="${width}" depth="${thickness}" height="${height}"/>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <xacro:ori_geo width="${width}" depth="${thickness}" height="${height}"/>
    </collision>
  </link>
</xacro:macro>

<xacro:macro name="corpus" params="prefix width depth height wall_thickness">
  <xacro:wall prefix="${prefix}_back" width="${width-2*wall_thickness}" height="${height-2*wall_thickness}" thickness="${wall_thickness}"/>
  
  <xacro:wall prefix="${prefix}_bottom" width="${width}" height="${depth}" thickness="${wall_thickness}"/>
  <joint name="${prefix}_bottom_joint" type="fixed">
    <origin xyz="0 -${depth/2-wall_thickness/2} -${height/2-wall_thickness/2}" rpy="${pi/2} 0 0"/>
    <parent link="${prefix}_back_wall"/>
    <child link="${prefix}_bottom_wall"/>
  </joint>
  

  <xacro:wall prefix="${prefix}_left" width="${depth}" height="${height-2*wall_thickness}" thickness="${wall_thickness}"/>
  <joint name="${prefix}_left_joint" type="fixed">
    <origin xyz="-${width/2-wall_thickness/2} -${depth/2-wall_thickness/2} 0" rpy="0 0 ${pi/2}"/>
    <parent link="${prefix}_back_wall"/>
    <child link="${prefix}_left_wall"/>
  </joint>

  <xacro:wall prefix="${prefix}_right" width="${depth}" height="${height-2*wall_thickness}" thickness="${wall_thickness}"/>
  <joint name="${prefix}_right_joint" type="fixed">
    <origin xyz="${width/2-wall_thickness/2} -${depth/2-wall_thickness/2} 0" rpy="0 0 ${pi/2}"/>
    <parent link="${prefix}_back_wall"/>
    <child link="${prefix}_right_wall"/>
  </joint>

  <xacro:wall prefix="${prefix}_top" width="${width}" height="${depth}" thickness="${wall_thickness}"/>
  <joint name="${prefix}_top_joint" type="fixed">
    <origin xyz="0 -${depth/2-wall_thickness/2} ${height/2-wall_thickness/2}" rpy="${pi/2} 0 0"/>
    <parent link="${prefix}_back_wall"/>
    <child link="${prefix}_top_wall"/>
  </joint>
</xacro:macro>

<xacro:macro name="drawer" params="index">
  <xacro:property name="drawer_height" value="${(total_height-2*wall_thickness-(num_drawers+1)*drawer_spacing)/num_drawers}"/>
  <xacro:corpus prefix="drawer${index}" 
              width="${total_width-2*(wall_thickness+drawer_spacing)}"
              depth="${drawer_height}"
              height="${total_depth-wall_thickness-drawer_spacing}"
              wall_thickness="${wall_thickness*0.5}"/>
  <joint name="drawer${index}_joint" type="prismatic">
    <origin xyz="0 -${(wall_thickness+drawer_spacing)/2} ${wall_thickness+drawer_spacing+0.5*0.5*wall_thickness + (index-1)*(drawer_height+drawer_spacing)}" rpy="-${pi/2} 0 0"/>
    <parent link="base_link"/>
    <child link="drawer${index}_back_wall"/>
    <axis xyz="0 -1 0"/>
    <dynamics damping="0.1"/>
    <limit lower="0.0" upper="1.5" effort="0.0" velocity="0.5"/>
  </joint>
</xacro:macro>



<link name="base_link"/>

<xacro:corpus prefix="frame" width="${total_width}" depth="${total_depth}" height="${total_height}" wall_thickness="${wall_thickness}"/>
<joint name="frame_joint" type="fixed">
  <origin xyz="0 ${total_depth/2-wall_thickness/2} ${total_height/2}" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="frame_back_wall"/>
</joint>


<!-- <xacro:drawer index="1"/>
<xacro:drawer index="2"/>
<xacro:drawer index="3"/> -->

<xacro:corpus prefix="drawer1" 
              width="${total_width-2*(wall_thickness+drawer_spacing)}"
              depth="${(total_height-2*wall_thickness-(num_drawers+1)*drawer_spacing)/num_drawers}"
              height="${total_depth-wall_thickness-drawer_spacing}"
              wall_thickness="${wall_thickness*0.5}"/>
<joint name="drawer1_joint" type="prismatic">
  <origin xyz="0 -${(wall_thickness+drawer_spacing)/2} ${1.7}" rpy="-${pi/2} 0 0"/>
  <parent link="base_link"/>
  <child link="drawer1_back_wall"/>
  <axis xyz="0 0 -1"/>
  <dynamics damping="0.0"/>
  <limit lower="-10.0" upper="10.5" effort="1.0" velocity="1.5"/>
</joint>



</robot>

